export const DEFAULT_CHARACTER_SCALE = 2
export const DEFAULT_CHARACTER_OFFSET_Y = 9
export const DEFAULT_CHARACTER_SHADOW_SCALE = DEFAULT_CHARACTER_SCALE * 0.9 // Tweak global shadow size here.
export const DEFAULT_CHARACTER_SHADOW_OPACITY = 0.4 // Tweak global shadow opacity here.

export const DEFAULT_CHARACTER_SHADOW = {
  sprite: "/pets/Shadow.png",
  width: 17,
  height: 6,
  scale: DEFAULT_CHARACTER_SHADOW_SCALE,
  opacity: DEFAULT_CHARACTER_SHADOW_OPACITY,
  offsetX: 0,
  offsetY: 2,
}

export const CHARACTER_ROSTER = [
  {
    id: "Bob",
    name: "Bob",
    spritesheet: "/pets/Basic character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Cerise",
    name: "Cerise",
    spritesheet: "/pets/Spring 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Zamy",
    name: "Zamy",
    spritesheet: "/pets/Autumn 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Shroomy",
    name: "Shroomy",
    spritesheet: "/pets/Autumn 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Giromon",
    name: "Giromon",
    spritesheet: "/pets/Autumn 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Faucheuse",
    name: "Faucheuse",
    spritesheet: "/pets/Autumn 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Bugz B",
    name: "Bugz B",
    spritesheet: "/pets/Basic Bunny character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Plantipot",
    name: "Plantipot",
    spritesheet: "/pets/Character 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Jordan",
    name: "Jordan",
    spritesheet: "/pets/Character 10 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Dylan",
    name: "Dylan",
    spritesheet: "/pets/Character 11 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Incognito",
    name: "Incognito",
    spritesheet: "/pets/Character 12 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Sbire",
    name: "Sbire",
    spritesheet: "/pets/Character 13 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Etchebest",
    name: "Etchebest",
    spritesheet: "/pets/Character 14 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "King",
    name: "King",
    spritesheet: "/pets/Character 15 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Bam-Boo",
    name: "Bam-Boo",
    spritesheet: "/pets/Character 16 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Tv",
    name: "Tv",
    spritesheet: "/pets/Character 17 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Definitely-not-a-Bot",
    name: "Definitely-not-a-Bot",
    spritesheet: "/pets/Character 18 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Bozo",
    name: "Bozo",
    spritesheet: "/pets/Character 19 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Ahouu",
    name: "Ahouu",
    spritesheet: "/pets/Character 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Gims",
    name: "Gims",
    spritesheet: "/pets/Character 20 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Sherriff",
    name: "Sherriff",
    spritesheet: "/pets/Character 21 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Golum",
    name: "Golum",
    spritesheet: "/pets/Character 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Classy",
    name: "Classy",
    spritesheet: "/pets/Character 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Lil Devil",
    name: "Lil Devil",
    spritesheet: "/pets/Character 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Azazel",
    name: "Azazel",
    spritesheet: "/pets/Character 6 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Astronaut",
    name: "Astronaut",
    spritesheet: "/pets/Character 7 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Ilhan",
    name: "Ilhan",
    spritesheet: "/pets/Character 8 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Norris",
    name: "Norris",
    spritesheet: "/pets/Character 9 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Gauvain",
    name: "Gauvain",
    spritesheet: "/pets/DG Knight 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Yvain",
    name: "Yvain",
    spritesheet: "/pets/DG Knight 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Perceval",
    name: "Perceval",
    spritesheet: "/pets/DG Knight 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Lancelot",
    name: "Lancelot",
    spritesheet: "/pets/DG Knight 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Gatito",
    name: "Gatito",
    spritesheet: "/pets/Gato v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Étoile",
    name: "Étoile",
    spritesheet: "/pets/Gato 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Chaussette",
    name: "Chaussette",
    spritesheet: "/pets/Gato 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Mia",
    name: "Mia",
    spritesheet: "/pets/Gato 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Caramel",
    name: "Caramel",
    spritesheet: "/pets/Gato 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Randy",
    name: "Randy",
    spritesheet: "/pets/Main Character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Sharky",
    name: "Sharky",
    spritesheet: "/pets/Special 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Hedwix",
    name: "Hedwix",
    spritesheet: "/pets/Special 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Tino the Dino",
    name: "Tino the Dino",
    spritesheet: "/pets/Special 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Alien",
    name: "Alien",
    spritesheet: "/pets/Special 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Pô",
    name: "Pô",
    spritesheet: "/pets/Special 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Merveille",
    name: "Merveille",
    spritesheet: "/pets/Spring 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Héliante",
    name: "Héliante",
    spritesheet: "/pets/Spring 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Bzzzee",
    name: "Bzzzee",
    spritesheet: "/pets/Spring 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Tuby",
    name: "Tuby",
    spritesheet: "/pets/Summer 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "LuffD",
    name: "LuffD",
    spritesheet: "/pets/Summer 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Timmy",
    name: "Timmy",
    spritesheet: "/pets/Summer 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Malibou",
    name: "Malibou",
    spritesheet: "/pets/Summer 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Harry",
    name: "Harry",
    spritesheet: "/pets/Winter 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Santa",
    name: "Santa",
    spritesheet: "/pets/Winter 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Rudolf",
    name: "Rudolf",
    spritesheet: "/pets/Winter 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "Olaf",
    name: "Olaf",
    spritesheet: "/pets/Winter 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
]

export const CHARACTER_ROSTER_BY_ID = Object.fromEntries(
  CHARACTER_ROSTER.map((character) => [character.id, character])
)

export const DEFAULT_CHARACTER_ID = CHARACTER_ROSTER[0]?.id || "character_01"
