import { WORLD_ATLAS_DATA } from '../utils/worldAtlasData';
import { getStartupPreloadChunks, prewarmChunk } from '../utils/worldAtlasFamilies';
import { setMovementLocked } from '../store/worldSlice';
import { LOADING_SCREEN_DEPTH } from './renderDepths';

// ── Config ────────────────────────────────────────────────────────────────────

/**
 * Chunks generated per async tick.  Each tick is a setTimeout(0) callback so
 * the browser can render a loading frame between ticks.  4–6 is a good balance:
 * fast enough to finish in <1 s, small enough to keep each tick under ~50 ms.
 */
const CHUNKS_PER_TICK = 4;

/** Hourglass animation frame duration in ms. */
const HOURGLASS_FRAME_MS    = 120;
const HOURGLASS_FRAME_COUNT = 8;

/** Row y-positions in Cursors & Pointers.png. */
const HOURGLASS_NORMAL_ROW_Y = 208;
const HOURGLASS_HOVER_ROW_Y  = 224;

/** Each source frame is 16×16 pixels. */
const HOURGLASS_FRAME_W = 16;
const HOURGLASS_FRAME_H = 16;

/** Render scale for the on-screen hourglass sprite. */
const HOURGLASS_SCALE = 3;

/** Phaser texture key — must match what MainScene.preload() loads. */
export const HOURGLASS_TEXTURE_KEY = 'hud_cursor_sheet';

// ── StartupPreloadSystem ──────────────────────────────────────────────────────

/**
 * Startup loading overlay + progressive chunk prewarm.
 *
 * The chunk queue is built from getStartupPreloadChunks(), which returns the
 * EXACT same set of chunks that primeWorldAtlasWindow(includePreload:true) will
 * target at runtime.  This guarantees that when the loading screen ends the
 * runtime prewarm finds remaining = 0 on the first call, producing no
 * post-startup generation spike.
 *
 * Chunks are sorted center-out so the innermost (active-range) chunks are
 * generated first and stay hot in the cache.
 *
 * Lifecycle:
 *   new StartupPreloadSystem(scene, { onComplete })
 *   system.startLoading()   ← once, from MainScene.create()
 *   …async ticks…
 *   onComplete()            ← overlay torn down, then this fires
 *   system.destroy()        ← safe to call any time (e.g. shutdown)
 */
export default class StartupPreloadSystem {
  constructor(scene, { onComplete }) {
    this._scene          = scene;
    this._onComplete     = onComplete;
    this._frameIndex     = 0;
    this._isHover        = false;
    this._done           = false;
    this._pendingChunks  = [];   // remaining missingChunks, spliced each tick
    this._totalMissing   = 0;   // for progress / debug
    this._warmedCount    = 0;   // chunks generated by this system
    this._tickHandle     = null;
    this._frameTimer     = null;
    this._overlay        = null;
    this._hourglassImg   = null;
    this._loadingText    = null;
    this._onPointerMove  = null;
  }

  // ── Public API ──────────────────────────────────────────────────────────────

  startLoading() {
    setMovementLocked(true);

    const cam      = this._scene.cameras.main;
    const viewport = { width: cam.width, height: cam.height };

    // Build the exact preload chunk list from the real getChunkWindow so the
    // queue perfectly matches what primeWorldAtlasWindow will check at runtime.
    const info = getStartupPreloadChunks(0, 0, WORLD_ATLAS_DATA, viewport);
    this._pendingChunks = info.missingChunks.slice();
    this._totalMissing  = info.missingCount;

    console.info(
      `[Startup] preload range ${info.preloadChunkRange.minChunkX},${info.preloadChunkRange.minChunkY}` +
      ` → ${info.preloadChunkRange.maxChunkX},${info.preloadChunkRange.maxChunkY}` +
      `  total=${info.totalCount}  missing=${info.missingCount}` +
      `  viewport=${cam.width}×${cam.height}`
    );

    // Frames registered BEFORE image is created so Phaser never shows the full
    // spritesheet texture as a fallback on the first rendered frame.
    this._registerHourglassFrames();
    this._setupOverlay();

    this._frameTimer = this._scene.time.addEvent({
      delay: HOURGLASS_FRAME_MS,
      repeat: -1,
      callback: this._advanceFrame,
      callbackScope: this,
    });

    // Hover detection: switch spritesheet row without resetting frame index.
    const hgX   = cam.width  - HOURGLASS_FRAME_W * HOURGLASS_SCALE * 0.5 - 8;
    const hgY   = cam.height - HOURGLASS_FRAME_H * HOURGLASS_SCALE * 0.5 - 8;
    const halfW = HOURGLASS_FRAME_W * HOURGLASS_SCALE * 0.5 + 4;
    const halfH = HOURGLASS_FRAME_H * HOURGLASS_SCALE * 0.5 + 4;

    this._onPointerMove = (ptr) => {
      this._isHover =
        Math.abs(ptr.x - hgX) <= halfW &&
        Math.abs(ptr.y - hgY) <= halfH;
    };
    this._scene.input.on('pointermove', this._onPointerMove);

    if (this._pendingChunks.length === 0) {
      // Everything already cached (e.g. hot reload) — complete immediately.
      this._completeLoading();
    } else {
      this._scheduleNextTick();
    }
  }

  destroy() {
    if (this._tickHandle != null) {
      clearTimeout(this._tickHandle);
      this._tickHandle = null;
    }
    this._teardownOverlay();
    if (!this._done) {
      setMovementLocked(false);
      this._done = true;
    }
    this._scene = null;
  }

  // ── Overlay ─────────────────────────────────────────────────────────────────

  _setupOverlay() {
    const cam = this._scene.cameras.main;
    const w   = cam.width;
    const h   = cam.height;

    this._overlay = this._scene.add.graphics()
      .setScrollFactor(0)
      .setDepth(LOADING_SCREEN_DEPTH);
    this._overlay.fillStyle(0x000000, 1);
    this._overlay.fillRect(0, 0, w, h);

    this._loadingText = this._scene.add
      .text(w * 0.5, h * 0.5, 'Loading world...', {
        font: '12px monospace',
        fill: '#ffffff',
        alpha: 0.7,
      })
      .setOrigin(0.5, 0.5)
      .setScrollFactor(0)
      .setDepth(LOADING_SCREEN_DEPTH + 1);

    if (this._scene.textures.exists(HOURGLASS_TEXTURE_KEY)) {
      const hgX = w - HOURGLASS_FRAME_W * HOURGLASS_SCALE * 0.5 - 8;
      const hgY = h - HOURGLASS_FRAME_H * HOURGLASS_SCALE * 0.5 - 8;
      this._hourglassImg = this._scene.add
        .image(hgX, hgY, HOURGLASS_TEXTURE_KEY, 'hg_n0')
        .setScale(HOURGLASS_SCALE)
        .setScrollFactor(0)
        .setDepth(LOADING_SCREEN_DEPTH + 1)
        .setOrigin(0.5, 0.5);
    }
  }

  _registerHourglassFrames() {
    if (!this._scene.textures.exists(HOURGLASS_TEXTURE_KEY)) return;
    const tex = this._scene.textures.get(HOURGLASS_TEXTURE_KEY);
    for (let i = 0; i < HOURGLASS_FRAME_COUNT; i++) {
      const srcX = i * HOURGLASS_FRAME_W;
      if (!tex.has(`hg_n${i}`)) tex.add(`hg_n${i}`, 0, srcX, HOURGLASS_NORMAL_ROW_Y, HOURGLASS_FRAME_W, HOURGLASS_FRAME_H);
      if (!tex.has(`hg_h${i}`)) tex.add(`hg_h${i}`, 0, srcX, HOURGLASS_HOVER_ROW_Y,  HOURGLASS_FRAME_W, HOURGLASS_FRAME_H);
    }
  }

  _teardownOverlay() {
    this._frameTimer?.remove(false);
    this._frameTimer = null;
    if (this._onPointerMove && this._scene?.input) {
      this._scene.input.off('pointermove', this._onPointerMove);
      this._onPointerMove = null;
    }
    this._overlay?.destroy();      this._overlay     = null;
    this._hourglassImg?.destroy(); this._hourglassImg = null;
    this._loadingText?.destroy();  this._loadingText  = null;
  }

  // ── Animation ───────────────────────────────────────────────────────────────

  _advanceFrame() {
    this._frameIndex = (this._frameIndex + 1) % HOURGLASS_FRAME_COUNT;
    if (this._hourglassImg) {
      const key = this._isHover
        ? `hg_h${this._frameIndex}`
        : `hg_n${this._frameIndex}`;
      this._hourglassImg.setFrame(key);
    }
  }

  // ── Chunk prewarming ─────────────────────────────────────────────────────────

  _scheduleNextTick() {
    this._tickHandle = setTimeout(() => this._processTick(), 0);
  }

  _processTick() {
    if (this._done || !this._scene) return;

    const batch = this._pendingChunks.splice(0, CHUNKS_PER_TICK);
    for (const { chunkX, chunkY } of batch) {
      prewarmChunk(WORLD_ATLAS_DATA, chunkX, chunkY);
      this._warmedCount++;
    }

    if (this._pendingChunks.length > 0) {
      this._scheduleNextTick();
    } else {
      this._completeLoading();
    }
  }

  _completeLoading() {
    if (this._done) return;
    this._done = true;

    console.info(
      `[Startup] prewarm complete — warmed=${this._warmedCount}` +
      ` (${this._totalMissing} were missing at start)`
    );

    setMovementLocked(false);
    this._teardownOverlay();
    this._onComplete?.();
  }
}
