export const DEFAULT_CHARACTER_SCALE = 2.5
export const DEFAULT_CHARACTER_OFFSET_Y = 9
export const DEFAULT_CHARACTER_SHADOW_SCALE = DEFAULT_CHARACTER_SCALE * 0.9 // Tweak global shadow size here.
export const DEFAULT_CHARACTER_SHADOW_OPACITY = 0.4 // Tweak global shadow opacity here.

export const DEFAULT_CHARACTER_SHADOW = {
  sprite: "/pets/Shadow.png",
  width: 17,
  height: 6,
  scale: DEFAULT_CHARACTER_SHADOW_SCALE,
  opacity: DEFAULT_CHARACTER_SHADOW_OPACITY,
  offsetX: 0,
  offsetY: 2,
}

export const CHARACTER_ROSTER = [
  {
    id: "basic_character",
    name: "Basic Character",
    spritesheet: "/pets/Basic character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "spring_4",
    name: "Spring 4",
    spritesheet: "/pets/Spring 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "autumn_1",
    name: "Autumn 1",
    spritesheet: "/pets/Autumn 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "autumn_2",
    name: "Autumn 2",
    spritesheet: "/pets/Autumn 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "autumn_3",
    name: "Autumn 3",
    spritesheet: "/pets/Autumn 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "autumn_4",
    name: "Autumn 4",
    spritesheet: "/pets/Autumn 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "basic_bunny_character",
    name: "Basic Bunny Character",
    spritesheet: "/pets/Basic Bunny character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_1",
    name: "Character 1",
    spritesheet: "/pets/Character 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_10",
    name: "Character 10",
    spritesheet: "/pets/Character 10 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_11",
    name: "Character 11",
    spritesheet: "/pets/Character 11 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_12",
    name: "Character 12",
    spritesheet: "/pets/Character 12 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_13",
    name: "Character 13",
    spritesheet: "/pets/Character 13 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_14",
    name: "Character 14",
    spritesheet: "/pets/Character 14 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_15",
    name: "Character 15",
    spritesheet: "/pets/Character 15 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_16",
    name: "Character 16",
    spritesheet: "/pets/Character 16 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_17",
    name: "Character 17",
    spritesheet: "/pets/Character 17 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_18",
    name: "Character 18",
    spritesheet: "/pets/Character 18 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_19",
    name: "Character 19",
    spritesheet: "/pets/Character 19 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_2",
    name: "Character 2",
    spritesheet: "/pets/Character 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_20",
    name: "Character 20",
    spritesheet: "/pets/Character 20 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_21",
    name: "Character 21",
    spritesheet: "/pets/Character 21 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_3",
    name: "Character 3",
    spritesheet: "/pets/Character 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_4",
    name: "Character 4",
    spritesheet: "/pets/Character 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_5",
    name: "Character 5",
    spritesheet: "/pets/Character 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_6",
    name: "Character 6",
    spritesheet: "/pets/Character 6 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_7",
    name: "Character 7",
    spritesheet: "/pets/Character 7 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_8",
    name: "Character 8",
    spritesheet: "/pets/Character 8 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "character_9",
    name: "Character 9",
    spritesheet: "/pets/Character 9 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "dg_knight_1",
    name: "DG Knight 1",
    spritesheet: "/pets/DG Knight 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "dg_knight_2",
    name: "DG Knight 2",
    spritesheet: "/pets/DG Knight 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "dg_knight_3",
    name: "DG Knight 3",
    spritesheet: "/pets/DG Knight 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "dg_knight_4",
    name: "DG Knight 4",
    spritesheet: "/pets/DG Knight 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "gato",
    name: "Gato",
    spritesheet: "/pets/Gato v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "gato_2",
    name: "Gato 2",
    spritesheet: "/pets/Gato 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "gato_3",
    name: "Gato 3",
    spritesheet: "/pets/Gato 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "gato_4",
    name: "Gato 4",
    spritesheet: "/pets/Gato 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "gato_5",
    name: "Gato 5",
    spritesheet: "/pets/Gato 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "main_character",
    name: "Main Character",
    spritesheet: "/pets/Main Character v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "special_1",
    name: "Special 1",
    spritesheet: "/pets/Special 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "special_2",
    name: "Special 2",
    spritesheet: "/pets/Special 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "special_3",
    name: "Special 3",
    spritesheet: "/pets/Special 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "special_4",
    name: "Special 4",
    spritesheet: "/pets/Special 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "special_5",
    name: "Special 5",
    spritesheet: "/pets/Special 5 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "spring_1",
    name: "Spring 1",
    spritesheet: "/pets/Spring 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "spring_2",
    name: "Spring 2",
    spritesheet: "/pets/Spring 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "spring_3",
    name: "Spring 3",
    spritesheet: "/pets/Spring 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "summer_1",
    name: "Summer 1",
    spritesheet: "/pets/Summer 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "summer_2",
    name: "Summer 2",
    spritesheet: "/pets/Summer 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "summer_3",
    name: "Summer 3",
    spritesheet: "/pets/Summer 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "summer_4",
    name: "Summer 4",
    spritesheet: "/pets/Summer 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "winter_1",
    name: "Winter 1",
    spritesheet: "/pets/Winter 1 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "winter_2",
    name: "Winter 2",
    spritesheet: "/pets/Winter 2 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "winter_3",
    name: "Winter 3",
    spritesheet: "/pets/Winter 3 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
  {
    id: "winter_4",
    name: "Winter 4",
    spritesheet: "/pets/Winter 4 v1.png",
    scale: DEFAULT_CHARACTER_SCALE,
    offsetX: 0,
    offsetY: 0,
    useTint: false,
    shadow: DEFAULT_CHARACTER_SHADOW,
  },
]

export const CHARACTER_ROSTER_BY_ID = Object.fromEntries(
  CHARACTER_ROSTER.map((character) => [character.id, character])
)

export const DEFAULT_CHARACTER_ID = CHARACTER_ROSTER[0]?.id || "character_01"
